/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminKeyResponse {
    /// User identifier.
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// Timestamp in UTC that represents when the admin key will expire. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "expirationTime", skip_serializing_if = "Option::is_none")]
    pub expiration_time: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl AdminKeyResponse {
    pub fn new() -> AdminKeyResponse {
        AdminKeyResponse {
            account_id: None,
            expiration_time: None,
        }
    }
}
