/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentLinks {
    /// Web UI link of the content.
    #[serde(rename = "webui", skip_serializing_if = "Option::is_none")]
    pub webui: Option<String>,
    /// Download link of the content.
    #[serde(rename = "download", skip_serializing_if = "Option::is_none")]
    pub download: Option<String>,
}

impl AttachmentLinks {
    pub fn new() -> AttachmentLinks {
        AttachmentLinks {
            webui: None,
            download: None,
        }
    }
}
