/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttachmentSortOrder : The sort fields for attachments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
/// The sort fields for attachments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttachmentSortOrder {
    #[serde(rename = "created-date")]
    CreatedDate,
    #[serde(rename = "-created-date")]
    CreatedDate2,
    #[serde(rename = "modified-date")]
    ModifiedDate,
    #[serde(rename = "-modified-date")]
    ModifiedDate2,
}

impl std::fmt::Display for AttachmentSortOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedDate => write!(f, "created-date"),
            Self::CreatedDate2 => write!(f, "-created-date"),
            Self::ModifiedDate => write!(f, "modified-date"),
            Self::ModifiedDate2 => write!(f, "-modified-date"),
        }
    }
}

impl Default for AttachmentSortOrder {
    fn default() -> AttachmentSortOrder {
        Self::CreatedDate
    }
}
