/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogPostBulk {
    /// ID of the blog post.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::BlogPostContentStatus>,
    /// Title of the blog post.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// ID of the space the blog post is in.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// The account ID of the user who created this blog post originally.
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Date and time when the blog post was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::BodyBulk>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::AbstractPageLinks>>,
}

impl BlogPostBulk {
    pub fn new() -> BlogPostBulk {
        BlogPostBulk {
            id: None,
            status: None,
            title: None,
            space_id: None,
            author_id: None,
            created_at: None,
            version: None,
            body: None,
            _links: None,
        }
    }
}
