/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlogPostNestedBodyWrite : Body of the blog post. Only one body format should be specified as the property for this object, e.g. `storage`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogPostNestedBodyWrite {
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<models::BlogPostBodyWrite>>,
    #[serde(rename = "atlas_doc_format", skip_serializing_if = "Option::is_none")]
    pub atlas_doc_format: Option<Box<models::BlogPostBodyWrite>>,
    #[serde(rename = "wiki", skip_serializing_if = "Option::is_none")]
    pub wiki: Option<Box<models::BlogPostBodyWrite>>,
}

impl BlogPostNestedBodyWrite {
    /// Body of the blog post. Only one body format should be specified as the property for this object, e.g. `storage`.
    pub fn new() -> BlogPostNestedBodyWrite {
        BlogPostNestedBodyWrite {
            storage: None,
            atlas_doc_format: None,
            wiki: None,
        }
    }
}
