/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogPostSingle {
    /// ID of the blog post.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::BlogPostContentStatus>,
    /// Title of the blog post.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// ID of the space the blog post is in.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// The account ID of the user who created this blog post originally.
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Date and time when the blog post was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::BodySingle>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Box<models::AttachmentSingleLabels>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::AttachmentSingleProperties>>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Box<models::AttachmentSingleOperations>>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<Box<models::BlogPostSingleLikes>>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::AttachmentSingleVersions>>,
    /// Whether the blog post has been favorited by the current user.
    #[serde(
        rename = "isFavoritedByCurrentUser",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_favorited_by_current_user: Option<bool>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::AbstractPageLinks>>,
}

impl BlogPostSingle {
    pub fn new() -> BlogPostSingle {
        BlogPostSingle {
            id: None,
            status: None,
            title: None,
            space_id: None,
            author_id: None,
            created_at: None,
            version: None,
            body: None,
            labels: None,
            properties: None,
            operations: None,
            likes: None,
            versions: None,
            is_favorited_by_current_user: None,
            _links: None,
        }
    }
}
