/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BodyType {
    /// Type of content representation used for the value field.
    #[serde(rename = "representation", skip_serializing_if = "Option::is_none")]
    pub representation: Option<String>,
    /// Body of the content, in the format found in the representation field.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl BodyType {
    pub fn new() -> BodyType {
        BodyType {
            representation: None,
            value: None,
        }
    }
}
