/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClassificationLevel : A unit of [data classification](https://support.atlassian.com/security-and-access-policies/docs/what-is-data-classification/) defined by an organiation.  A classification level may be associated with specific storage and handling requirements or expectations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClassificationLevel {
    /// The ID of the classification level.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ClassificationLevelStatus>,
    /// The order of the classification level object.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<f64>,
    /// The name of the classification level object.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of the classification level object.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The guideline of the classification level object.
    #[serde(rename = "guideline", skip_serializing_if = "Option::is_none")]
    pub guideline: Option<String>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::ClassificationLevelColor>,
}

impl ClassificationLevel {
    /// A unit of [data classification](https://support.atlassian.com/security-and-access-policies/docs/what-is-data-classification/) defined by an organiation.  A classification level may be associated with specific storage and handling requirements or expectations.
    pub fn new() -> ClassificationLevel {
        ClassificationLevel {
            id: None,
            status: None,
            order: None,
            name: None,
            description: None,
            guideline: None,
            color: None,
        }
    }
}
