/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClassificationLevelColor {
    #[serde(rename = "RED")]
    Red,
    #[serde(rename = "RED_BOLD")]
    RedBold,
    #[serde(rename = "ORANGE")]
    Orange,
    #[serde(rename = "YELLOW")]
    Yellow,
    #[serde(rename = "GREEN")]
    Green,
    #[serde(rename = "BLUE")]
    Blue,
    #[serde(rename = "NAVY")]
    Navy,
    #[serde(rename = "TEAL")]
    Teal,
    #[serde(rename = "PURPLE")]
    Purple,
    #[serde(rename = "GREY")]
    Grey,
    #[serde(rename = "LIME")]
    Lime,
}

impl std::fmt::Display for ClassificationLevelColor {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Red => write!(f, "RED"),
            Self::RedBold => write!(f, "RED_BOLD"),
            Self::Orange => write!(f, "ORANGE"),
            Self::Yellow => write!(f, "YELLOW"),
            Self::Green => write!(f, "GREEN"),
            Self::Blue => write!(f, "BLUE"),
            Self::Navy => write!(f, "NAVY"),
            Self::Teal => write!(f, "TEAL"),
            Self::Purple => write!(f, "PURPLE"),
            Self::Grey => write!(f, "GREY"),
            Self::Lime => write!(f, "LIME"),
        }
    }
}

impl Default for ClassificationLevelColor {
    fn default() -> ClassificationLevelColor {
        Self::Red
    }
}
