/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentPropertyUpdateRequestVersion : New version number and associated message
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentPropertyUpdateRequestVersion {
    /// Version number of the new version. Should be 1 more than the current version number.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    /// Message to be associated with the new version.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ContentPropertyUpdateRequestVersion {
    /// New version number and associated message
    pub fn new() -> ContentPropertyUpdateRequestVersion {
        ContentPropertyUpdateRequestVersion {
            number: None,
            message: None,
        }
    }
}
