/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentIdToContentTypeResponse {
    /// JSON object containing all requested content ids as keys and their associated content types as the values. Duplicate content ids in the request will be returned under a single key in the response. For built-in content types, the enumerations are as specified. Custom content ids will be mapped to their associated type.
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<
        std::collections::HashMap<String, models::ContentIdToContentTypeResponseResultsValue>,
    >,
}

impl ContentIdToContentTypeResponse {
    pub fn new() -> ContentIdToContentTypeResponse {
        ContentIdToContentTypeResponse { results: None }
    }
}
