/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateInlineCommentModelInlineCommentProperties : Object describing the text to highlight on the page/blog post. Only applicable for top level inline comments (not replies) and required in that case.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInlineCommentModelInlineCommentProperties {
    /// The text to highlight
    #[serde(rename = "textSelection", skip_serializing_if = "Option::is_none")]
    pub text_selection: Option<String>,
    /// The number of matches for the selected text on the page (should be strictly greater than textSelectionMatchIndex)
    #[serde(
        rename = "textSelectionMatchCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_selection_match_count: Option<i32>,
    /// The match index to highlight. This is zero-based. E.g. if you have 3 occurrences of \"hello world\" on a page  and you want to highlight the second occurrence, you should pass 1 for textSelectionMatchIndex and 3 for textSelectionMatchCount.
    #[serde(
        rename = "textSelectionMatchIndex",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_selection_match_index: Option<i32>,
}

impl CreateInlineCommentModelInlineCommentProperties {
    /// Object describing the text to highlight on the page/blog post. Only applicable for top level inline comments (not replies) and required in that case.
    pub fn new() -> CreateInlineCommentModelInlineCommentProperties {
        CreateInlineCommentModelInlineCommentProperties {
            text_selection: None,
            text_selection_match_count: None,
            text_selection_match_index: None,
        }
    }
}
