/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWhiteboardRequest {
    /// ID of the space.
    #[serde(rename = "spaceId")]
    pub space_id: String,
    /// Title of the whiteboard.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The parent content ID of the whiteboard.
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// Providing a template key will add that template to the new whiteboard.
    #[serde(rename = "templateKey", skip_serializing_if = "Option::is_none")]
    pub template_key: Option<TemplateKey>,
    /// If templateKey is provided, locale will decide which language the template will be created with. If locale is omitted, the user's locale will be used.
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<Locale>,
}

impl CreateWhiteboardRequest {
    pub fn new(space_id: String) -> CreateWhiteboardRequest {
        CreateWhiteboardRequest {
            space_id,
            title: None,
            parent_id: None,
            template_key: None,
            locale: None,
        }
    }
}
/// Providing a template key will add that template to the new whiteboard.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TemplateKey {
    #[serde(rename = "2x2-prioritization")]
    Variant2x2Prioritization,
    #[serde(rename = "4ls-retro")]
    Variant4lsRetro,
    #[serde(rename = "annual-calendar")]
    AnnualCalendar,
    #[serde(rename = "brainwriting")]
    Brainwriting,
    #[serde(rename = "concept-map")]
    ConceptMap,
    #[serde(rename = "crazy-8s")]
    Crazy8s,
    #[serde(rename = "daily-sync")]
    DailySync,
    #[serde(rename = "disruptive-brainstorm")]
    DisruptiveBrainstorm,
    #[serde(rename = "dot-voting")]
    DotVoting,
    #[serde(rename = "elevator-pitch")]
    ElevatorPitch,
    #[serde(rename = "flow-chart")]
    FlowChart,
    #[serde(rename = "gap-analysis")]
    GapAnalysis,
    #[serde(rename = "ice-breakers")]
    IceBreakers,
    #[serde(rename = "incident-postmortem")]
    IncidentPostmortem,
    #[serde(rename = "journey-mapping-kit")]
    JourneyMappingKit,
    #[serde(rename = "kanban-board")]
    KanbanBoard,
    #[serde(rename = "lean-coffee")]
    LeanCoffee,
    #[serde(rename = "network-of-teams")]
    NetworkOfTeams,
    #[serde(rename = "org-chart")]
    OrgChart,
    #[serde(rename = "pi-planning")]
    PiPlanning,
    #[serde(rename = "prioritization")]
    Prioritization,
    #[serde(rename = "prioritization-experiment")]
    PrioritizationExperiment,
    #[serde(rename = "product-roadmap")]
    ProductRoadmap,
    #[serde(rename = "product-vision-board")]
    ProductVisionBoard,
    #[serde(rename = "rice")]
    Rice,
    #[serde(rename = "sailboat-retro")]
    SailboatRetro,
    #[serde(rename = "service-blueprint")]
    ServiceBlueprint,
    #[serde(rename = "simple-retrospective")]
    SimpleRetrospective,
    #[serde(rename = "sprint-planning")]
    SprintPlanning,
    #[serde(rename = "sticky-note-pack")]
    StickyNotePack,
    #[serde(rename = "swimlanes")]
    Swimlanes,
    #[serde(rename = "team-formation-guide")]
    TeamFormationGuide,
    #[serde(rename = "timeline")]
    Timeline,
    #[serde(rename = "timeline-workflow")]
    TimelineWorkflow,
    #[serde(rename = "user-story-map")]
    UserStoryMap,
    #[serde(rename = "workflow")]
    Workflow,
    #[serde(rename = "vision-board")]
    VisionBoard,
    #[serde(rename = "venn-diagram")]
    VennDiagram,
    #[serde(rename = "storyboard")]
    Storyboard,
    #[serde(rename = "action-plan")]
    ActionPlan,
    #[serde(rename = "root-cause-analysis")]
    RootCauseAnalysis,
    #[serde(rename = "executive-summary")]
    ExecutiveSummary,
    #[serde(rename = "stakeholder-mapping")]
    StakeholderMapping,
    #[serde(rename = "annual-calendar-2025-2026")]
    AnnualCalendar20252026,
    #[serde(rename = "health-monitor")]
    HealthMonitor,
    #[serde(rename = "okr-planning")]
    OkrPlanning,
    #[serde(rename = "swot-analysis")]
    SwotAnalysis,
    #[serde(rename = "poker-planning")]
    PokerPlanning,
    #[serde(rename = "fishbone-diagram")]
    FishboneDiagram,
    #[serde(rename = "risk-assessment")]
    RiskAssessment,
    #[serde(rename = "bounded-context")]
    BoundedContext,
    #[serde(rename = "hopes-and-fears")]
    HopesAndFears,
    #[serde(rename = "swimlane-vertical")]
    SwimlaneVertical,
}

impl Default for TemplateKey {
    fn default() -> TemplateKey {
        Self::Variant2x2Prioritization
    }
}
/// If templateKey is provided, locale will decide which language the template will be created with. If locale is omitted, the user's locale will be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Locale {
    #[serde(rename = "de-DE")]
    DeDe,
    #[serde(rename = "cs-CZ")]
    CsCz,
    #[serde(rename = "ko-KR")]
    KoKr,
    #[serde(rename = "fr-FR")]
    FrFr,
    #[serde(rename = "it-IT")]
    ItIt,
    #[serde(rename = "ja-JP")]
    JaJp,
    #[serde(rename = "nl-NL")]
    NlNl,
    #[serde(rename = "nb-NO")]
    NbNo,
    #[serde(rename = "da-DK")]
    DaDk,
    #[serde(rename = "sv-SE")]
    SvSe,
    #[serde(rename = "fi-FI")]
    FiFi,
    #[serde(rename = "ru-RU")]
    RuRu,
    #[serde(rename = "pl-PL")]
    PlPl,
    #[serde(rename = "tr-TR")]
    TrTr,
    #[serde(rename = "hu-HU")]
    HuHu,
    #[serde(rename = "en-GB")]
    EnGb,
    #[serde(rename = "en-US")]
    EnUs,
    #[serde(rename = "pt-BR")]
    PtBr,
    #[serde(rename = "zh-CN")]
    ZhCn,
    #[serde(rename = "zh-TW")]
    ZhTw,
    #[serde(rename = "es-ES")]
    EsEs,
}

impl Default for Locale {
    fn default() -> Locale {
        Self::DeDe
    }
}
