/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFooterCommentModel {
    /// ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply.
    #[serde(rename = "blogPostId", skip_serializing_if = "Option::is_none")]
    pub blog_post_id: Option<String>,
    /// ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply.
    #[serde(rename = "pageId", skip_serializing_if = "Option::is_none")]
    pub page_id: Option<String>,
    /// ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment.
    #[serde(rename = "parentCommentId", skip_serializing_if = "Option::is_none")]
    pub parent_comment_id: Option<String>,
    /// ID of the attachment, if intending to create a comment against an attachment.
    #[serde(rename = "attachmentId", skip_serializing_if = "Option::is_none")]
    pub attachment_id: Option<String>,
    /// ID of the custom content, if intending to create a comment against a custom content.
    #[serde(rename = "customContentId", skip_serializing_if = "Option::is_none")]
    pub custom_content_id: Option<String>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::CreateFooterCommentModelBody>>,
}

impl CreateFooterCommentModel {
    pub fn new() -> CreateFooterCommentModel {
        CreateFooterCommentModel {
            blog_post_id: None,
            page_id: None,
            parent_comment_id: None,
            attachment_id: None,
            custom_content_id: None,
            body: None,
        }
    }
}
