/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBlogPostRequest {
    /// ID of the space
    #[serde(rename = "spaceId")]
    pub space_id: String,
    /// The status of the blog post, specifies if the blog post will be created as a new blog post or a draft
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Title of the blog post, required if creating non-draft.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::CreateBlogPostRequestBody>>,
    /// Created date of the blog post in the format of \"yyyy-MM-ddTHH:mm:ss.SSSZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl CreateBlogPostRequest {
    pub fn new(space_id: String) -> CreateBlogPostRequest {
        CreateBlogPostRequest {
            space_id,
            status: None,
            title: None,
            body: None,
            created_at: None,
        }
    }
}
/// The status of the blog post, specifies if the blog post will be created as a new blog post or a draft
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for Status {
    fn default() -> Status {
        Self::Current
    }
}
