/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePage200Response {
    /// ID of the page.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ContentStatus>,
    /// Title of the page.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// ID of the space the page is in.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// ID of the parent page, or null if there is no parent page.
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "parentType", skip_serializing_if = "Option::is_none")]
    pub parent_type: Option<models::ParentContentType>,
    /// Position of child page within the given parent page tree.
    #[serde(
        rename = "position",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub position: Option<Option<i32>>,
    /// The account ID of the user who created this page originally.
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// The account ID of the user who owns this page.
    #[serde(
        rename = "ownerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<String>>,
    /// The account ID of the user who owned this page previously, or null if there is no previous owner.
    #[serde(
        rename = "lastOwnerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_owner_id: Option<Option<String>>,
    /// Date and time when the page was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::BodySingle>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Box<models::AttachmentSingleLabels>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::AttachmentSingleProperties>>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Box<models::AttachmentSingleOperations>>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<Box<models::BlogPostSingleLikes>>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::AttachmentSingleVersions>>,
    /// Whether the page has been favorited by the current user.
    #[serde(
        rename = "isFavoritedByCurrentUser",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_favorited_by_current_user: Option<bool>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::GetAttachmentById200ResponseAllOfLinks>>,
}

impl CreatePage200Response {
    pub fn new() -> CreatePage200Response {
        CreatePage200Response {
            id: None,
            status: None,
            title: None,
            space_id: None,
            parent_id: None,
            parent_type: None,
            position: None,
            author_id: None,
            owner_id: None,
            last_owner_id: None,
            created_at: None,
            version: None,
            body: None,
            labels: None,
            properties: None,
            operations: None,
            likes: None,
            versions: None,
            is_favorited_by_current_user: None,
            _links: None,
        }
    }
}
