/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCustomContentRequestBody {
    CustomContentBodyWrite(Box<models::CustomContentBodyWrite>),
    CustomContentNestedBodyWrite(Box<models::CustomContentNestedBodyWrite>),
}

impl Default for CreateCustomContentRequestBody {
    fn default() -> Self {
        Self::CustomContentBodyWrite(Default::default())
    }
}
/// Type of content representation used for the value field.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Representation {
    #[serde(rename = "storage")]
    Storage,
    #[serde(rename = "atlas_doc_format")]
    AtlasDocFormat,
    #[serde(rename = "raw")]
    Raw,
}

impl Default for Representation {
    fn default() -> Representation {
        Self::Storage
    }
}
