/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSpaceRequest {
    /// The name of the space to be created.
    #[serde(rename = "name")]
    pub name: String,
    /// The key for the new space. See [Space Keys](https://support.atlassian.com/confluence-cloud/docs/create-a-space/). If the key property is not provided, the alias property is required to be used instead.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// This field will be used as the new identifier for the space in confluence page URLs. If the alias property is not provided, the key property is required to be used instead. Maximum 255 alphanumeric characters in length.
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::CreateSpaceRequestDescription>>,
    #[serde(rename = "roleAssignments", skip_serializing_if = "Option::is_none")]
    pub role_assignments: Option<Vec<models::CreateSpaceRequestRoleAssignmentsInner>>,
    /// The id of the space to copy the space access configuration from.
    #[serde(
        rename = "copySpaceAccessConfiguration",
        skip_serializing_if = "Option::is_none"
    )]
    pub copy_space_access_configuration: Option<i32>,
    /// Whether to create the space as private.
    #[serde(rename = "createPrivateSpace", skip_serializing_if = "Option::is_none")]
    pub create_private_space: Option<bool>,
    /// The key of the template to use.
    #[serde(rename = "templateKey", skip_serializing_if = "Option::is_none")]
    pub template_key: Option<String>,
}

impl CreateSpaceRequest {
    pub fn new(name: String) -> CreateSpaceRequest {
        CreateSpaceRequest {
            name,
            key: None,
            alias: None,
            description: None,
            role_assignments: None,
            copy_space_access_configuration: None,
            create_private_space: None,
            template_key: None,
        }
    }
}
