/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSpaceRoleRequest {
    /// Name of the space role
    #[serde(rename = "name")]
    pub name: String,
    /// Description for the space role
    #[serde(rename = "description")]
    pub description: String,
    /// The ids of the space permissions associated with the space role. Sample value \"read/space\"; retrieve ids from responses returned by [GET /space-permissions](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-space-permissions/#api-space-permissions-get) endpoint
    #[serde(rename = "spacePermissions")]
    pub space_permissions: Vec<String>,
}

impl CreateSpaceRoleRequest {
    pub fn new(
        name: String,
        description: String,
        space_permissions: Vec<String>,
    ) -> CreateSpaceRoleRequest {
        CreateSpaceRoleRequest {
            name,
            description,
            space_permissions,
        }
    }
}
