/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomContentSingle {
    /// ID of the custom content.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of custom content.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ContentStatus>,
    /// Title of the custom content.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// ID of the space the custom content is in.  Note: This is always returned, regardless of if the custom content has a container that is a space.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// ID of the containing page.  Note: This is only returned if the custom content has a container that is a page.
    #[serde(rename = "pageId", skip_serializing_if = "Option::is_none")]
    pub page_id: Option<String>,
    /// ID of the containing blog post.  Note: This is only returned if the custom content has a container that is a blog post.
    #[serde(rename = "blogPostId", skip_serializing_if = "Option::is_none")]
    pub blog_post_id: Option<String>,
    /// ID of the containing custom content.  Note: This is only returned if the custom content has a container that is custom content.
    #[serde(rename = "customContentId", skip_serializing_if = "Option::is_none")]
    pub custom_content_id: Option<String>,
    /// The account ID of the user who created this custom content originally.
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Date and time when the custom content was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Box<models::AttachmentSingleLabels>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::AttachmentSingleProperties>>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Box<models::AttachmentSingleOperations>>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::AttachmentSingleVersions>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::CustomContentBodySingle>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::CustomContentLinks>>,
}

impl CustomContentSingle {
    pub fn new() -> CustomContentSingle {
        CustomContentSingle {
            id: None,
            r#type: None,
            status: None,
            title: None,
            space_id: None,
            page_id: None,
            blog_post_id: None,
            custom_content_id: None,
            author_id: None,
            created_at: None,
            version: None,
            labels: None,
            properties: None,
            operations: None,
            versions: None,
            body: None,
            _links: None,
        }
    }
}
