/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomContentBodyRepresentation : The formats a custom content body can be represented as. A subset of BodyRepresentation.
/// The formats a custom content body can be represented as. A subset of BodyRepresentation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomContentBodyRepresentation {
    #[serde(rename = "raw")]
    Raw,
    #[serde(rename = "storage")]
    Storage,
    #[serde(rename = "atlas_doc_format")]
    AtlasDocFormat,
}

impl std::fmt::Display for CustomContentBodyRepresentation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Raw => write!(f, "raw"),
            Self::Storage => write!(f, "storage"),
            Self::AtlasDocFormat => write!(f, "atlas_doc_format"),
        }
    }
}

impl Default for CustomContentBodyRepresentation {
    fn default() -> CustomContentBodyRepresentation {
        Self::Raw
    }
}
