/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedVersion {
    /// The current version number.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    /// The account ID of the user who created this version.
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Message associated with the current version.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Date and time when the version was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions.
    #[serde(rename = "minorEdit", skip_serializing_if = "Option::is_none")]
    pub minor_edit: Option<bool>,
    /// Describes if the content type is modified in this version (e.g. page to blog)
    #[serde(
        rename = "contentTypeModified",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_type_modified: Option<bool>,
    /// The account IDs of users that collaborated on this version.
    #[serde(rename = "collaborators", skip_serializing_if = "Option::is_none")]
    pub collaborators: Option<Vec<String>>,
    /// The version number of the version prior to this current content update.
    #[serde(rename = "prevVersion", skip_serializing_if = "Option::is_none")]
    pub prev_version: Option<i32>,
    /// The version number of the version after this current content update.
    #[serde(rename = "nextVersion", skip_serializing_if = "Option::is_none")]
    pub next_version: Option<i32>,
}

impl DetailedVersion {
    pub fn new() -> DetailedVersion {
        DetailedVersion {
            number: None,
            author_id: None,
            message: None,
            created_at: None,
            minor_edit: None,
            content_type_modified: None,
            collaborators: None,
            prev_version: None,
            next_version: None,
        }
    }
}
