/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnableAdminKeyRequest {
    /// The requested duration of admin key access in minutes, up to a maximum of 60 minutes, after which the issued admin key will automatically expire.
    #[serde(rename = "durationInMinutes", skip_serializing_if = "Option::is_none")]
    pub duration_in_minutes: Option<i32>,
}

impl EnableAdminKeyRequest {
    pub fn new() -> EnableAdminKeyRequest {
        EnableAdminKeyRequest {
            duration_in_minutes: None,
        }
    }
}
