/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAttachmentById200Response {
    /// ID of the attachment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ContentStatus>,
    /// Title of the comment.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Date and time when the attachment was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// ID of the containing page.  Note: This is only returned if the attachment has a container that is a page.
    #[serde(rename = "pageId", skip_serializing_if = "Option::is_none")]
    pub page_id: Option<String>,
    /// ID of the containing blog post.  Note: This is only returned if the attachment has a container that is a blog post.
    #[serde(rename = "blogPostId", skip_serializing_if = "Option::is_none")]
    pub blog_post_id: Option<String>,
    /// ID of the containing custom content.  Note: This is only returned if the attachment has a container that is custom content.
    #[serde(rename = "customContentId", skip_serializing_if = "Option::is_none")]
    pub custom_content_id: Option<String>,
    /// Media Type for the attachment.
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
    /// Media Type description for the attachment.
    #[serde(
        rename = "mediaTypeDescription",
        skip_serializing_if = "Option::is_none"
    )]
    pub media_type_description: Option<String>,
    /// Comment for the attachment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// File ID of the attachment. This is the ID referenced in `atlas_doc_format` bodies and is distinct from the attachment ID.
    #[serde(rename = "fileId", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// File size of the attachment.
    #[serde(rename = "fileSize", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
    /// WebUI link of the attachment.
    #[serde(rename = "webuiLink", skip_serializing_if = "Option::is_none")]
    pub webui_link: Option<String>,
    /// Download link of the attachment.
    #[serde(rename = "downloadLink", skip_serializing_if = "Option::is_none")]
    pub download_link: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Box<models::AttachmentSingleLabels>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::AttachmentSingleProperties>>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Box<models::AttachmentSingleOperations>>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::AttachmentSingleVersions>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::GetAttachmentById200ResponseAllOfLinks>>,
}

impl GetAttachmentById200Response {
    pub fn new() -> GetAttachmentById200Response {
        GetAttachmentById200Response {
            id: None,
            status: None,
            title: None,
            created_at: None,
            page_id: None,
            blog_post_id: None,
            custom_content_id: None,
            media_type: None,
            media_type_description: None,
            comment: None,
            file_id: None,
            file_size: None,
            webui_link: None,
            download_link: None,
            version: None,
            labels: None,
            properties: None,
            operations: None,
            versions: None,
            _links: None,
        }
    }
}
