/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineCommentModel {
    /// ID of the comment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ContentStatus>,
    /// Title of the comment.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// ID of the blog post containing the comment if the comment is on a blog post.
    #[serde(rename = "blogPostId", skip_serializing_if = "Option::is_none")]
    pub blog_post_id: Option<String>,
    /// ID of the page containing the comment if the comment is on a page.
    #[serde(rename = "pageId", skip_serializing_if = "Option::is_none")]
    pub page_id: Option<String>,
    /// ID of the parent comment if the comment is a reply.
    #[serde(rename = "parentCommentId", skip_serializing_if = "Option::is_none")]
    pub parent_comment_id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::Version>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::BodySingle>>,
    /// Atlassian Account ID of last person who modified the resolve state of the comment. Null until comment is resolved or reopened.
    #[serde(
        rename = "resolutionLastModifierId",
        skip_serializing_if = "Option::is_none"
    )]
    pub resolution_last_modifier_id: Option<String>,
    /// Timestamp of the last modification to the comment's resolution status. Null until comment is resolved or reopened.
    #[serde(
        rename = "resolutionLastModifiedAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub resolution_last_modified_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "resolutionStatus", skip_serializing_if = "Option::is_none")]
    pub resolution_status: Option<models::InlineCommentResolutionStatus>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::InlineCommentModelProperties>>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Box<models::AttachmentSingleOperations>>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<Box<models::BlogPostSingleLikes>>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::AttachmentSingleVersions>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::CommentLinks>>,
}

impl InlineCommentModel {
    pub fn new() -> InlineCommentModel {
        InlineCommentModel {
            id: None,
            status: None,
            title: None,
            blog_post_id: None,
            page_id: None,
            parent_comment_id: None,
            version: None,
            body: None,
            resolution_last_modifier_id: None,
            resolution_last_modified_at: None,
            resolution_status: None,
            properties: None,
            operations: None,
            likes: None,
            versions: None,
            _links: None,
        }
    }
}
