/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InlineCommentResolutionStatus : Inline comment resolution status
/// Inline comment resolution status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InlineCommentResolutionStatus {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "reopened")]
    Reopened,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "dangling")]
    Dangling,
}

impl std::fmt::Display for InlineCommentResolutionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Open => write!(f, "open"),
            Self::Reopened => write!(f, "reopened"),
            Self::Resolved => write!(f, "resolved"),
            Self::Dangling => write!(f, "dangling"),
        }
    }
}

impl Default for InlineCommentResolutionStatus {
    fn default() -> InlineCommentResolutionStatus {
        Self::Open
    }
}
