/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineCommentModelProperties {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::ContentProperty>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::OptionalFieldMeta>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::OptionalFieldLinks>>,
    /// Property value used to reference the highlighted element in DOM.
    #[serde(rename = "inlineMarkerRef", skip_serializing_if = "Option::is_none")]
    pub inline_marker_ref: Option<String>,
    /// Text that is highlighted.
    #[serde(
        rename = "inlineOriginalSelection",
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_original_selection: Option<String>,
}

impl InlineCommentModelProperties {
    pub fn new() -> InlineCommentModelProperties {
        InlineCommentModelProperties {
            results: None,
            meta: None,
            _links: None,
            inline_marker_ref: None,
            inline_original_selection: None,
        }
    }
}
