/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiEntityLinks {
    /// Used for pagination. Contains the relative URL for the next set of results, using a cursor query parameter. This property will not be present if there is no additional data available.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// Base url of the Confluence site.
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
}

impl MultiEntityLinks {
    pub fn new() -> MultiEntityLinks {
        MultiEntityLinks {
            next: None,
            base: None,
        }
    }
}
