/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnlyArchivedAndCurrentContentStatus : The status of the content.
/// The status of the content.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnlyArchivedAndCurrentContentStatus {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(other)]
    Unknown,
}

impl std::fmt::Display for OnlyArchivedAndCurrentContentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Current => write!(f, "current"),
            Self::Archived => write!(f, "archived"),
            Self::Draft => write!(f, "draft"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl Default for OnlyArchivedAndCurrentContentStatus {
    fn default() -> OnlyArchivedAndCurrentContentStatus {
        Self::Current
    }
}
