/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionalFieldMeta {
    /// Indicates if there are more available results that can be fetched.
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// A token that can be used in the query parameter of the endpoint returned in the `_links` property to retrieve the next set of results.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl OptionalFieldMeta {
    pub fn new() -> OptionalFieldMeta {
        OptionalFieldMeta {
            has_more: None,
            cursor: None,
        }
    }
}
