/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostPageClassificationLevelRequest {
    /// Status of the content.
    #[serde(rename = "status")]
    pub status: Status,
}

impl PostPageClassificationLevelRequest {
    pub fn new(status: Status) -> PostPageClassificationLevelRequest {
        PostPageClassificationLevelRequest { status }
    }
}
/// Status of the content.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for Status {
    fn default() -> Status {
        Self::Current
    }
}
