/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrimaryBodyRepresentation : The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
/// The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrimaryBodyRepresentation {
    #[serde(rename = "storage")]
    Storage,
    #[serde(rename = "atlas_doc_format")]
    AtlasDocFormat,
}

impl std::fmt::Display for PrimaryBodyRepresentation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Storage => write!(f, "storage"),
            Self::AtlasDocFormat => write!(f, "atlas_doc_format"),
        }
    }
}

impl Default for PrimaryBodyRepresentation {
    fn default() -> PrimaryBodyRepresentation {
        Self::Storage
    }
}
