/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrincipalType : The principal type.
/// The principal type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrincipalType {
    #[serde(rename = "USER")]
    User,
    #[serde(rename = "GROUP")]
    Group,
    #[serde(rename = "ACCESS_CLASS")]
    AccessClass,
}

impl std::fmt::Display for PrincipalType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::User => write!(f, "USER"),
            Self::Group => write!(f, "GROUP"),
            Self::AccessClass => write!(f, "ACCESS_CLASS"),
        }
    }
}

impl Default for PrincipalType {
    fn default() -> PrincipalType {
        Self::User
    }
}
