/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Principal : The principal of the role assignment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Principal {
    #[serde(rename = "principalType", skip_serializing_if = "Option::is_none")]
    pub principal_type: Option<models::PrincipalType>,
    /// The principal ID.
    #[serde(rename = "principalId", skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<String>,
}

impl Principal {
    /// The principal of the role assignment.
    pub fn new() -> Principal {
        Principal {
            principal_type: None,
            principal_id: None,
        }
    }
}
