/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedactionPointer {
    /// JSON pointer indicating the exact location within the content structure  where redaction should be applied. Points to the text node containing the content to redact.
    #[serde(rename = "pointer")]
    pub pointer: String,
    /// Starting character index (zero-based) within the target text where redaction begins.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<i32>,
    /// Ending character index (zero-based) within the target text where redaction ends (exclusive). Must be greater than or equal to 'from' value.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<i32>,
    /// Optional human-readable reason for the redaction. Used for audit trails and compliance documentation.
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
}

impl RedactionPointer {
    pub fn new(pointer: String) -> RedactionPointer {
        RedactionPointer {
            pointer,
            from: None,
            to: None,
            reason: None,
        }
    }
}
