/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetSpaceRoleAssignmentsRequestInner {
    #[serde(rename = "principal")]
    pub principal: Box<models::Principal>,
    /// The role to which the principal is assigned.
    #[serde(rename = "roleId", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
}

impl SetSpaceRoleAssignmentsRequestInner {
    pub fn new(principal: models::Principal) -> SetSpaceRoleAssignmentsRequestInner {
        SetSpaceRoleAssignmentsRequestInner {
            principal: Box::new(principal),
            role_id: None,
        }
    }
}
