/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpacePermission {
    /// The identifier for the space permission.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The display name for the space permission.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Describes the space permission’s usage.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The permissions required for this permission to be enabled.
    #[serde(
        rename = "requiredPermissionIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub required_permission_ids: Option<Vec<String>>,
}

impl SpacePermission {
    pub fn new() -> SpacePermission {
        SpacePermission {
            id: None,
            display_name: None,
            description: None,
            required_permission_ids: None,
        }
    }
}
