/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpaceDescription : Contains fields for each representation type requested.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpaceDescription {
    #[serde(rename = "plain", skip_serializing_if = "Option::is_none")]
    pub plain: Option<Box<models::BodyType>>,
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<Box<models::BodyType>>,
}

impl SpaceDescription {
    /// Contains fields for each representation type requested.
    pub fn new() -> SpaceDescription {
        SpaceDescription {
            plain: None,
            view: None,
        }
    }
}
