/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpacePermissionAssignmentOperation : The operation the space permission corresponds to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpacePermissionAssignmentOperation {
    /// The type of operation.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Key>,
    /// The type of entity the operation type targets.
    #[serde(rename = "targetType", skip_serializing_if = "Option::is_none")]
    pub target_type: Option<TargetType>,
}

impl SpacePermissionAssignmentOperation {
    /// The operation the space permission corresponds to.
    pub fn new() -> SpacePermissionAssignmentOperation {
        SpacePermissionAssignmentOperation {
            key: None,
            target_type: None,
        }
    }
}
/// The type of operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Key {
    #[serde(rename = "use")]
    Use,
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "copy")]
    Copy,
    #[serde(rename = "move")]
    Move,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "purge")]
    Purge,
    #[serde(rename = "purge_version")]
    PurgeVersion,
    #[serde(rename = "administer")]
    Administer,
    #[serde(rename = "restore")]
    Restore,
    #[serde(rename = "create_space")]
    CreateSpace,
    #[serde(rename = "restrict_content")]
    RestrictContent,
    #[serde(rename = "archive")]
    Archive,
}

impl Default for Key {
    fn default() -> Key {
        Self::Use
    }
}
/// The type of entity the operation type targets.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TargetType {
    #[serde(rename = "page")]
    Page,
    #[serde(rename = "blogpost")]
    Blogpost,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "attachment")]
    Attachment,
    #[serde(rename = "whiteboard")]
    Whiteboard,
    #[serde(rename = "database")]
    Database,
    #[serde(rename = "embed")]
    Embed,
    #[serde(rename = "folder")]
    Folder,
    #[serde(rename = "space")]
    Space,
    #[serde(rename = "application")]
    Application,
    #[serde(rename = "userProfile")]
    UserProfile,
}

impl Default for TargetType {
    fn default() -> TargetType {
        Self::Page
    }
}
