/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpaceStatus : The status of the space.
/// The status of the space.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpaceStatus {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "archived")]
    Archived,
}

impl std::fmt::Display for SpaceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Current => write!(f, "current"),
            Self::Archived => write!(f, "archived"),
        }
    }
}

impl Default for SpaceStatus {
    fn default() -> SpaceStatus {
        Self::Current
    }
}
