/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpaceType : The type of space.
/// The type of space.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpaceType {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "collaboration")]
    Collaboration,
    #[serde(rename = "knowledge_base")]
    KnowledgeBase,
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "onboarding")]
    Onboarding,
    #[serde(rename = "xflow_sample_space")]
    XflowSampleSpace,
}

impl std::fmt::Display for SpaceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Global => write!(f, "global"),
            Self::Collaboration => write!(f, "collaboration"),
            Self::KnowledgeBase => write!(f, "knowledge_base"),
            Self::Personal => write!(f, "personal"),
            Self::System => write!(f, "system"),
            Self::Onboarding => write!(f, "onboarding"),
            Self::XflowSampleSpace => write!(f, "xflow_sample_space"),
        }
    }
}

impl Default for SpaceType {
    fn default() -> SpaceType {
        Self::Global
    }
}
