/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBlogPostRequest {
    /// Id of the blog post.
    #[serde(rename = "id")]
    pub id: String,
    /// The updated status of the blog post.  Note, if you change the status of a blog post from 'current' to 'draft' and it has an existing draft, the existing draft will be deleted in favor of the updated draft. Additionally, this endpoint can be used to restore a 'trashed' or 'deleted' blog post to 'current' status. For restoration, blog post contents will not be updated and only the blog post status will be changed.
    #[serde(rename = "status")]
    pub status: Status,
    /// Title of the blog post.
    #[serde(rename = "title")]
    pub title: String,
    /// ID of the containing space.  This currently **does not support moving the blog post to a different space**.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    #[serde(rename = "body")]
    pub body: Box<models::CreateBlogPostRequestBody>,
    #[serde(rename = "version")]
    pub version: Box<models::UpdateBlogPostRequestVersion>,
    /// Created date of the blog post in the format of \"yyyy-MM-ddTHH:mm:ss.SSSZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl UpdateBlogPostRequest {
    pub fn new(
        id: String,
        status: Status,
        title: String,
        body: models::CreateBlogPostRequestBody,
        version: models::UpdateBlogPostRequestVersion,
    ) -> UpdateBlogPostRequest {
        UpdateBlogPostRequest {
            id,
            status,
            title,
            space_id: None,
            body: Box::new(body),
            version: Box::new(version),
            created_at: None,
        }
    }
}
/// The updated status of the blog post.  Note, if you change the status of a blog post from 'current' to 'draft' and it has an existing draft, the existing draft will be deleted in favor of the updated draft. Additionally, this endpoint can be used to restore a 'trashed' or 'deleted' blog post to 'current' status. For restoration, blog post contents will not be updated and only the blog post status will be changed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for Status {
    fn default() -> Status {
        Self::Current
    }
}
