/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTaskRequest {
    /// ID of the task.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Local ID of the task. This ID is local to the corresponding page or blog post.
    #[serde(rename = "localId", skip_serializing_if = "Option::is_none")]
    pub local_id: Option<String>,
    /// ID of the space the task is in.
    #[serde(rename = "spaceId", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// ID of the page the task is in.
    #[serde(rename = "pageId", skip_serializing_if = "Option::is_none")]
    pub page_id: Option<String>,
    /// ID of the blog post the task is in.
    #[serde(rename = "blogPostId", skip_serializing_if = "Option::is_none")]
    pub blog_post_id: Option<String>,
    /// Status of the task.
    #[serde(rename = "status")]
    pub status: Status,
    /// Account ID of the user who created this task.
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// Account ID of the user to whom this task is assigned.
    #[serde(rename = "assignedTo", skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<String>,
    /// Account ID of the user who completed this task.
    #[serde(rename = "completedBy", skip_serializing_if = "Option::is_none")]
    pub completed_by: Option<String>,
    /// Date and time when the task was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date and time when the task was updated. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date and time when the task is due. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "dueAt", skip_serializing_if = "Option::is_none")]
    pub due_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date and time when the task was completed. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
    #[serde(rename = "completedAt", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl UpdateTaskRequest {
    pub fn new(status: Status) -> UpdateTaskRequest {
        UpdateTaskRequest {
            id: None,
            local_id: None,
            space_id: None,
            page_id: None,
            blog_post_id: None,
            status,
            created_by: None,
            assigned_to: None,
            completed_by: None,
            created_at: None,
            updated_at: None,
            due_at: None,
            completed_at: None,
        }
    }
}
/// Status of the task.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl Default for Status {
    fn default() -> Status {
        Self::Complete
    }
}
