/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Display name of the user.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Time zone of the user. Depending on the user's privacy setting, this may return null.
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    /// Space ID of the user's personal space. Returns null, if no personal space for the user.
    #[serde(rename = "personalSpaceId", skip_serializing_if = "Option::is_none")]
    pub personal_space_id: Option<String>,
    /// Whether the user is an external collaborator.
    #[serde(
        rename = "isExternalCollaborator",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_external_collaborator: Option<bool>,
    #[serde(rename = "accountStatus", skip_serializing_if = "Option::is_none")]
    pub account_status: Option<models::AccountStatus>,
    /// Account ID of the user.
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The email address of the user. Depending on the user's privacy setting, this may return an empty string.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<models::AccountType>,
    /// Public name of the user.
    #[serde(rename = "publicName", skip_serializing_if = "Option::is_none")]
    pub public_name: Option<String>,
    #[serde(
        rename = "profilePicture",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_picture: Option<Option<Box<models::Icon>>>,
}

impl User {
    pub fn new() -> User {
        User {
            display_name: None,
            time_zone: None,
            personal_space_id: None,
            is_external_collaborator: None,
            account_status: None,
            account_id: None,
            email: None,
            account_type: None,
            public_name: None,
            profile_picture: None,
        }
    }
}
