/*
 * The Confluence Cloud REST API v2
 *
 * This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WhiteboardLinks {
    /// Web UI link of the content.
    #[serde(rename = "webui", skip_serializing_if = "Option::is_none")]
    pub webui: Option<String>,
    /// Edit UI link of the content.
    #[serde(rename = "editui", skip_serializing_if = "Option::is_none")]
    pub editui: Option<String>,
}

impl WhiteboardLinks {
    pub fn new() -> WhiteboardLinks {
        WhiteboardLinks {
            webui: None,
            editui: None,
        }
    }
}
