/*
 * The Confluence Cloud REST API - Atla v1 partial
 *
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LongTask {
    /// the ARI for the long task, based on its ID
    #[serde(rename = "ari", skip_serializing_if = "Option::is_none")]
    pub ari: Option<String>,
    /// a unique identifier for the long task
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "links")]
    pub links: models::LongTaskLinks,
}

impl LongTask {
    pub fn new(id: String, links: models::LongTaskLinks) -> LongTask {
        LongTask {
            ari: None,
            id,
            links,
        }
    }
}
