/*
 * The Confluence Cloud REST API - Atla v1 partial
 *
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpaceUpdate : The properties of a space that can be updated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpaceUpdate {
    /// The updated name of the space.
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<Box<models::SpaceDescriptionCreate>>>,
    /// The updated homepage for this space
    #[serde(
        rename = "homepage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub homepage: Option<Option<serde_json::Value>>,
    /// The updated type for this space.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The updated status for this space.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<String>>,
}

impl SpaceUpdate {
    /// The properties of a space that can be updated.
    pub fn new() -> SpaceUpdate {
        SpaceUpdate {
            name: None,
            description: None,
            homepage: None,
            r#type: None,
            status: None,
        }
    }
}
